# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/macecchi/Desktop/labickinect/CMakeLists.txt\
/Users/macecchi/Desktop/labickinect/xcode/CMakeFiles/CMakeCCompiler.cmake\
/Users/macecchi/Desktop/labickinect/xcode/CMakeFiles/CMakeCXXCompiler.cmake\
/Users/macecchi/Desktop/labickinect/xcode/CMakeFiles/CMakeSystem.cmake\
/opt/local/lib/vtk-5.10/CMake/vtkMakeInstantiator.cmake\
/opt/local/lib/vtk-5.10/UseVTK.cmake\
/opt/local/lib/vtk-5.10/VTKConfig.cmake\
/opt/local/lib/vtk-5.10/VTKConfigQt.cmake\
/opt/local/lib/vtk-5.10/VTKConfigVersion.cmake\
/opt/local/lib/vtk-5.10/VTKTargets-release.cmake\
/opt/local/lib/vtk-5.10/VTKTargets.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeImportBuildSettings.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU-C.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU-CXX.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/opt/local/share/cmake-2.8/Modules/FindBoost.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/opt/local/share/cmake-2.8/Modules/FindPkgConfig.cmake\
/opt/local/share/cmake-2.8/Modules/FindVTK.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-GNU-C.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-GNU-CXX.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-GNU.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/UnixPaths.cmake\
/usr/local/share/OpenCV/OpenCVConfig-version.cmake\
/usr/local/share/OpenCV/OpenCVConfig.cmake\
/usr/local/share/pcl-1.6/PCLConfig.cmake\
/usr/local/share/pcl-1.6/PCLConfigVersion.cmake
	/opt/local/bin/cmake -H/Users/macecchi/Desktop/labickinect -B/Users/macecchi/Desktop/labickinect/xcode
