# DO NOT EDIT
# This makefile makes sure all linkable targets are
# up-to-date with anything they link to
default:
	echo "Do not invoke directly"

# For each target create a dummy rule so the target does not have to exist
/opt/local/lib/libboost_system-mt.dylib:
/opt/local/lib/libboost_filesystem-mt.dylib:
/opt/local/lib/libboost_thread-mt.dylib:
/opt/local/lib/libboost_date_time-mt.dylib:
/opt/local/lib/libboost_iostreams-mt.dylib:
/usr/local/lib/libpcl_common.dylib:
/usr/local/lib/libpcl_octree.dylib:
/usr/lib/libOpenNI.dylib:
/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib:
/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib:
/opt/local/lib/vtk-5.10/libvtkHybrid.5.10.0.dylib:
/usr/local/lib/libpcl_io.dylib:
/opt/local/lib/libflann_cpp_s-gd.a:
/usr/local/lib/libpcl_kdtree.dylib:
/usr/local/lib/libpcl_search.dylib:
/usr/local/lib/libpcl_sample_consensus.dylib:
/usr/local/lib/libpcl_filters.dylib:
/usr/local/lib/libpcl_segmentation.dylib:
/usr/local/lib/libpcl_visualization.dylib:
/usr/local/lib/libpcl_features.dylib:
/usr/local/lib/libqhull.dylib:
/usr/local/lib/libpcl_surface.dylib:
/usr/local/lib/libpcl_registration.dylib:
/usr/local/lib/libpcl_keypoints.dylib:
/usr/local/lib/libpcl_tracking.dylib:
/usr/local/lib/libpcl_apps.dylib:
/usr/local/lib/libopencv_calib3d.dylib:
/usr/local/lib/libopencv_contrib.dylib:
/usr/local/lib/libopencv_core.dylib:
/usr/local/lib/libopencv_features2d.dylib:
/usr/local/lib/libopencv_flann.dylib:
/usr/local/lib/libopencv_gpu.dylib:
/usr/local/lib/libopencv_highgui.dylib:
/usr/local/lib/libopencv_imgproc.dylib:
/usr/local/lib/libopencv_legacy.dylib:
/usr/local/lib/libopencv_ml.dylib:
/usr/local/lib/libopencv_nonfree.dylib:
/usr/local/lib/libopencv_objdetect.dylib:
/usr/local/lib/libopencv_photo.dylib:
/usr/local/lib/libopencv_stitching.dylib:
/usr/local/lib/libopencv_ts.dylib:
/usr/local/lib/libopencv_video.dylib:
/usr/local/lib/libopencv_videostab.dylib:
/opt/local/lib/vtk-5.10/libvtkGraphics.5.10.0.dylib:
/opt/local/lib/vtk-5.10/libvtkImaging.5.10.0.dylib:
/opt/local/lib/libQtGui.dylib:
/opt/local/lib/libQtSql.dylib:
/opt/local/lib/libQtCore.dylib:
/opt/local/lib/vtk-5.10/libvtkIO.5.10.0.dylib:
/opt/local/lib/vtk-5.10/libvtkFiltering.5.10.0.dylib:
/opt/local/lib/vtk-5.10/libvtksys.5.10.0.dylib:
/opt/local/lib/libflann_cpp_s.a:


# Rules to remove targets that are older than anything to which they
# link.  This forces Xcode to relink the targets from scratch.  It
# does not seem to check these dependencies itself.
PostBuild.labickinect.Debug:
/Users/macecchi/Desktop/labickinect/xcode/Debug/labickinect:\
	/opt/local/lib/libboost_system-mt.dylib\
	/opt/local/lib/libboost_filesystem-mt.dylib\
	/opt/local/lib/libboost_thread-mt.dylib\
	/opt/local/lib/libboost_date_time-mt.dylib\
	/opt/local/lib/libboost_iostreams-mt.dylib\
	/usr/local/lib/libpcl_common.dylib\
	/usr/local/lib/libpcl_octree.dylib\
	/usr/lib/libOpenNI.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkHybrid.5.10.0.dylib\
	/usr/local/lib/libpcl_io.dylib\
	/opt/local/lib/libflann_cpp_s-gd.a\
	/usr/local/lib/libpcl_kdtree.dylib\
	/usr/local/lib/libpcl_search.dylib\
	/usr/local/lib/libpcl_sample_consensus.dylib\
	/usr/local/lib/libpcl_filters.dylib\
	/usr/local/lib/libpcl_segmentation.dylib\
	/usr/local/lib/libpcl_visualization.dylib\
	/usr/local/lib/libpcl_features.dylib\
	/usr/local/lib/libqhull.dylib\
	/usr/local/lib/libpcl_surface.dylib\
	/usr/local/lib/libpcl_registration.dylib\
	/usr/local/lib/libpcl_keypoints.dylib\
	/usr/local/lib/libpcl_tracking.dylib\
	/usr/local/lib/libpcl_apps.dylib\
	/usr/local/lib/libopencv_calib3d.dylib\
	/usr/local/lib/libopencv_contrib.dylib\
	/usr/local/lib/libopencv_core.dylib\
	/usr/local/lib/libopencv_features2d.dylib\
	/usr/local/lib/libopencv_flann.dylib\
	/usr/local/lib/libopencv_gpu.dylib\
	/usr/local/lib/libopencv_highgui.dylib\
	/usr/local/lib/libopencv_imgproc.dylib\
	/usr/local/lib/libopencv_legacy.dylib\
	/usr/local/lib/libopencv_ml.dylib\
	/usr/local/lib/libopencv_nonfree.dylib\
	/usr/local/lib/libopencv_objdetect.dylib\
	/usr/local/lib/libopencv_photo.dylib\
	/usr/local/lib/libopencv_stitching.dylib\
	/usr/local/lib/libopencv_ts.dylib\
	/usr/local/lib/libopencv_video.dylib\
	/usr/local/lib/libopencv_videostab.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkGraphics.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkImaging.5.10.0.dylib\
	/opt/local/lib/libQtGui.dylib\
	/opt/local/lib/libQtSql.dylib\
	/opt/local/lib/libQtCore.dylib\
	/opt/local/lib/vtk-5.10/libvtkIO.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkFiltering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtksys.5.10.0.dylib
	/bin/rm -f /Users/macecchi/Desktop/labickinect/xcode/Debug/labickinect


PostBuild.labickinect.Release:
/Users/macecchi/Desktop/labickinect/xcode/Release/labickinect:\
	/opt/local/lib/libboost_system-mt.dylib\
	/opt/local/lib/libboost_filesystem-mt.dylib\
	/opt/local/lib/libboost_thread-mt.dylib\
	/opt/local/lib/libboost_date_time-mt.dylib\
	/opt/local/lib/libboost_iostreams-mt.dylib\
	/usr/local/lib/libpcl_common.dylib\
	/usr/local/lib/libpcl_octree.dylib\
	/usr/lib/libOpenNI.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkHybrid.5.10.0.dylib\
	/usr/local/lib/libpcl_io.dylib\
	/opt/local/lib/libflann_cpp_s.a\
	/usr/local/lib/libpcl_kdtree.dylib\
	/usr/local/lib/libpcl_search.dylib\
	/usr/local/lib/libpcl_sample_consensus.dylib\
	/usr/local/lib/libpcl_filters.dylib\
	/usr/local/lib/libpcl_segmentation.dylib\
	/usr/local/lib/libpcl_visualization.dylib\
	/usr/local/lib/libpcl_features.dylib\
	/usr/local/lib/libqhull.dylib\
	/usr/local/lib/libpcl_surface.dylib\
	/usr/local/lib/libpcl_registration.dylib\
	/usr/local/lib/libpcl_keypoints.dylib\
	/usr/local/lib/libpcl_tracking.dylib\
	/usr/local/lib/libpcl_apps.dylib\
	/usr/local/lib/libopencv_calib3d.dylib\
	/usr/local/lib/libopencv_contrib.dylib\
	/usr/local/lib/libopencv_core.dylib\
	/usr/local/lib/libopencv_features2d.dylib\
	/usr/local/lib/libopencv_flann.dylib\
	/usr/local/lib/libopencv_gpu.dylib\
	/usr/local/lib/libopencv_highgui.dylib\
	/usr/local/lib/libopencv_imgproc.dylib\
	/usr/local/lib/libopencv_legacy.dylib\
	/usr/local/lib/libopencv_ml.dylib\
	/usr/local/lib/libopencv_nonfree.dylib\
	/usr/local/lib/libopencv_objdetect.dylib\
	/usr/local/lib/libopencv_photo.dylib\
	/usr/local/lib/libopencv_stitching.dylib\
	/usr/local/lib/libopencv_ts.dylib\
	/usr/local/lib/libopencv_video.dylib\
	/usr/local/lib/libopencv_videostab.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkGraphics.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkImaging.5.10.0.dylib\
	/opt/local/lib/libQtGui.dylib\
	/opt/local/lib/libQtSql.dylib\
	/opt/local/lib/libQtCore.dylib\
	/opt/local/lib/vtk-5.10/libvtkIO.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkFiltering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtksys.5.10.0.dylib
	/bin/rm -f /Users/macecchi/Desktop/labickinect/xcode/Release/labickinect


PostBuild.labickinect.MinSizeRel:
/Users/macecchi/Desktop/labickinect/xcode/MinSizeRel/labickinect:\
	/opt/local/lib/libboost_system-mt.dylib\
	/opt/local/lib/libboost_filesystem-mt.dylib\
	/opt/local/lib/libboost_thread-mt.dylib\
	/opt/local/lib/libboost_date_time-mt.dylib\
	/opt/local/lib/libboost_iostreams-mt.dylib\
	/usr/local/lib/libpcl_common.dylib\
	/usr/local/lib/libpcl_octree.dylib\
	/usr/lib/libOpenNI.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkHybrid.5.10.0.dylib\
	/usr/local/lib/libpcl_io.dylib\
	/opt/local/lib/libflann_cpp_s.a\
	/usr/local/lib/libpcl_kdtree.dylib\
	/usr/local/lib/libpcl_search.dylib\
	/usr/local/lib/libpcl_sample_consensus.dylib\
	/usr/local/lib/libpcl_filters.dylib\
	/usr/local/lib/libpcl_segmentation.dylib\
	/usr/local/lib/libpcl_visualization.dylib\
	/usr/local/lib/libpcl_features.dylib\
	/usr/local/lib/libqhull.dylib\
	/usr/local/lib/libpcl_surface.dylib\
	/usr/local/lib/libpcl_registration.dylib\
	/usr/local/lib/libpcl_keypoints.dylib\
	/usr/local/lib/libpcl_tracking.dylib\
	/usr/local/lib/libpcl_apps.dylib\
	/usr/local/lib/libopencv_calib3d.dylib\
	/usr/local/lib/libopencv_contrib.dylib\
	/usr/local/lib/libopencv_core.dylib\
	/usr/local/lib/libopencv_features2d.dylib\
	/usr/local/lib/libopencv_flann.dylib\
	/usr/local/lib/libopencv_gpu.dylib\
	/usr/local/lib/libopencv_highgui.dylib\
	/usr/local/lib/libopencv_imgproc.dylib\
	/usr/local/lib/libopencv_legacy.dylib\
	/usr/local/lib/libopencv_ml.dylib\
	/usr/local/lib/libopencv_nonfree.dylib\
	/usr/local/lib/libopencv_objdetect.dylib\
	/usr/local/lib/libopencv_photo.dylib\
	/usr/local/lib/libopencv_stitching.dylib\
	/usr/local/lib/libopencv_ts.dylib\
	/usr/local/lib/libopencv_video.dylib\
	/usr/local/lib/libopencv_videostab.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkGraphics.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkImaging.5.10.0.dylib\
	/opt/local/lib/libQtGui.dylib\
	/opt/local/lib/libQtSql.dylib\
	/opt/local/lib/libQtCore.dylib\
	/opt/local/lib/vtk-5.10/libvtkIO.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkFiltering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtksys.5.10.0.dylib
	/bin/rm -f /Users/macecchi/Desktop/labickinect/xcode/MinSizeRel/labickinect


PostBuild.labickinect.RelWithDebInfo:
/Users/macecchi/Desktop/labickinect/xcode/RelWithDebInfo/labickinect:\
	/opt/local/lib/libboost_system-mt.dylib\
	/opt/local/lib/libboost_filesystem-mt.dylib\
	/opt/local/lib/libboost_thread-mt.dylib\
	/opt/local/lib/libboost_date_time-mt.dylib\
	/opt/local/lib/libboost_iostreams-mt.dylib\
	/usr/local/lib/libpcl_common.dylib\
	/usr/local/lib/libpcl_octree.dylib\
	/usr/lib/libOpenNI.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkHybrid.5.10.0.dylib\
	/usr/local/lib/libpcl_io.dylib\
	/opt/local/lib/libflann_cpp_s.a\
	/usr/local/lib/libpcl_kdtree.dylib\
	/usr/local/lib/libpcl_search.dylib\
	/usr/local/lib/libpcl_sample_consensus.dylib\
	/usr/local/lib/libpcl_filters.dylib\
	/usr/local/lib/libpcl_segmentation.dylib\
	/usr/local/lib/libpcl_visualization.dylib\
	/usr/local/lib/libpcl_features.dylib\
	/usr/local/lib/libqhull.dylib\
	/usr/local/lib/libpcl_surface.dylib\
	/usr/local/lib/libpcl_registration.dylib\
	/usr/local/lib/libpcl_keypoints.dylib\
	/usr/local/lib/libpcl_tracking.dylib\
	/usr/local/lib/libpcl_apps.dylib\
	/usr/local/lib/libopencv_calib3d.dylib\
	/usr/local/lib/libopencv_contrib.dylib\
	/usr/local/lib/libopencv_core.dylib\
	/usr/local/lib/libopencv_features2d.dylib\
	/usr/local/lib/libopencv_flann.dylib\
	/usr/local/lib/libopencv_gpu.dylib\
	/usr/local/lib/libopencv_highgui.dylib\
	/usr/local/lib/libopencv_imgproc.dylib\
	/usr/local/lib/libopencv_legacy.dylib\
	/usr/local/lib/libopencv_ml.dylib\
	/usr/local/lib/libopencv_nonfree.dylib\
	/usr/local/lib/libopencv_objdetect.dylib\
	/usr/local/lib/libopencv_photo.dylib\
	/usr/local/lib/libopencv_stitching.dylib\
	/usr/local/lib/libopencv_ts.dylib\
	/usr/local/lib/libopencv_video.dylib\
	/usr/local/lib/libopencv_videostab.dylib\
	/opt/local/lib/vtk-5.10/libvtkRendering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkGraphics.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkImaging.5.10.0.dylib\
	/opt/local/lib/libQtGui.dylib\
	/opt/local/lib/libQtSql.dylib\
	/opt/local/lib/libQtCore.dylib\
	/opt/local/lib/vtk-5.10/libvtkIO.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkFiltering.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtkCommon.5.10.0.dylib\
	/opt/local/lib/vtk-5.10/libvtksys.5.10.0.dylib
	/bin/rm -f /Users/macecchi/Desktop/labickinect/xcode/RelWithDebInfo/labickinect


